<?php
/**
 * SimplePie
 *
 * A PHP-Based RSS and Atom Feed Framework.
 * Takes the hard work out of managing a complete RSS/Atom solution.
 *
 * Please note: This file is automatically generated by a build script. The
 * full original source is always available from http://simplepie.org/
 *
 * Copyright (c) 2004-2016, Ryan Parman, Sam Sneddon, Ryan McCue, and contributors
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 	* Redistributions of source code must retain the above copyright notice, this list of
 * 	  conditions and the following disclaimer.
 *
 * 	* Redistributions in binary form must reproduce the above copyright notice, this list
 * 	  of conditions and the following disclaimer in the documentation and/or other materials
 * 	  provided with the distribution.
 *
 * 	* Neither the name of the SimplePie Team nor the names of its contributors may be used
 * 	  to endorse or promote products derived from this software without specific prior
 * 	  written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
 * AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @package SimplePie
 * @copyright 2004-2016 Ryan Parman, Sam Sneddon, Ryan McCue
 * @author Ryan Parman
 * @author Sam Sneddon
 * @author Ryan McCue
 * @link http://simplepie.org/ SimplePie
 * @license http://www.opensource.org/licenses/bsd-license.php BSD License
 */

namespace SimplePie\Tests\Unit;

use PHPUnit\Framework\TestCase;
use SimplePie\Item;
use SimplePie\SimplePie;

class ItemTest extends TestCase
{
	public function testNamespacedClassExists()
	{
		$this->assertTrue(class_exists('SimplePie\Item'));
	}

	public function testClassExists()
	{
		$this->assertTrue(class_exists('SimplePie_Item'));
	}

	public function getContentDataProvider()
	{
		return [
			'Test Atom 0.3 Content' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<content>Item Description</content>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 DC 1.0 Description' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 DC 1.1 Description' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 Summary' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<summary>Item Description</summary>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 Content' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<content>Item Description</content>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 DC 1.0 Description' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 DC 1.1 Description' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 Summary' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<summary>Item Description</summary>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 0.3 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 0.3 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 1.0 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 1.0 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 DC 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 DC 1.1 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/">
	<item>
		<description>Item Description</description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description', // <description> isn't technically in 0.90, but we support it for compatibility
			],

			'Test RSS 0.91-Netscape Atom 0.3 Content' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 0.3 Summary' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 1.0 Content' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 1.0 Summary' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape DC 1.0 Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape DC 1.1 Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 0.3 Content' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 0.3 Summary' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 1.0 Content' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 1.0 Summary' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland DC 1.0 Description' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland DC 1.1 Description' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Description' => [
<<<EOT
<rss version="0.91">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 0.3 Content' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 0.3 Summary' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 1.0 Content' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 1.0 Summary' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 DC 1.0 Description' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 DC 1.1 Description' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Description' => [
<<<EOT
<rss version="0.92">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 0.3 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 0.3 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 1.0 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 1.0 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 DC 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 DC 1.1 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/">
	<item>
		<description>Item Description</description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 0.3 Content' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 0.3 Summary' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 1.0 Content' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 1.0 Summary' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 DC 1.0 Description' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 DC 1.1 Description' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Description' => [
<<<EOT
<rss version="2.0">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
		];
	}

	/**
	 * @dataProvider getContentDataProvider
	 */
	public function test_get_content($data, $expected)
	{
		$feed = new SimplePie();
		$feed->set_raw_data($data);
		$feed->enable_cache(false);
		$feed->init();

		$item = $feed->get_item(0);
		$this->assertInstanceOf(Item::class, $item);

		$this->assertSame($expected, $item->get_content());
	}

	public function getDateDataProvider()
	{
		return [
			'Test Atom 0.3 Created' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<created>2007-01-11T16:00:00Z</created>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 0.3 DC 1.0 Date' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 0.3 DC 1.1 Date' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 0.3 Issued' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<issued>2007-01-11T16:00:00Z</issued>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 0.3 Modified' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<modified>2007-01-11T16:00:00Z</modified>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 1.0 DC 1.0 Date' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 1.0 DC 1.1 Date' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 1.0 Published' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<published>2007-01-11T16:00:00Z</published>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Atom 1.0 Updated' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<updated>2007-01-11T16:00:00Z</updated>
	</entry>
</feed>
EOT
				,
				1168531200,
			],
			'Test Bug 876 Test 0' => [
<<<EOT
<rss version="2.0">
	<channel>
		<item>
			<pubDate></pubDate>
		</item>
	</channel>
</rss>
EOT
				,
				null,
			],
			'Test RSS 0.90 Atom 0.3 Created' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:created>2007-01-11T16:00:00Z</a:created>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 Atom 0.3 Issued' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:issued>2007-01-11T16:00:00Z</a:issued>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 Atom 0.3 Modified' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:modified>2007-01-11T16:00:00Z</a:modified>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 Atom 1.0 Published' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:published>2007-01-11T16:00:00Z</a:published>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 Atom 1.0 Updated' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:updated>2007-01-11T16:00:00Z</a:updated>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 DC 1.0 Date' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.90 DC 1.1 Date' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape Atom 0.3 Created' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:created>2007-01-11T16:00:00Z</a:created>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape Atom 0.3 Issued' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:issued>2007-01-11T16:00:00Z</a:issued>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape Atom 0.3 Modified' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:modified>2007-01-11T16:00:00Z</a:modified>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape Atom 1.0 Published' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:published>2007-01-11T16:00:00Z</a:published>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape Atom 1.0 Updated' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:updated>2007-01-11T16:00:00Z</a:updated>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape DC 1.0 Date' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Netscape DC 1.1 Date' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland Atom 0.3 Created' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:created>2007-01-11T16:00:00Z</a:created>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland Atom 0.3 Issued' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:issued>2007-01-11T16:00:00Z</a:issued>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland Atom 0.3 Modified' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:modified>2007-01-11T16:00:00Z</a:modified>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland Atom 1.0 Published' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:published>2007-01-11T16:00:00Z</a:published>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland Atom 1.0 Updated' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:updated>2007-01-11T16:00:00Z</a:updated>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland DC 1.0 Date' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.91-Userland DC 1.1 Date' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 Atom 0.3 Created' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:created>2007-01-11T16:00:00Z</a:created>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 Atom 0.3 Issued' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:issued>2007-01-11T16:00:00Z</a:issued>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 Atom 0.3 Modified' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:modified>2007-01-11T16:00:00Z</a:modified>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 Atom 1.0 Published' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:published>2007-01-11T16:00:00Z</a:published>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 Atom 1.0 Updated' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:updated>2007-01-11T16:00:00Z</a:updated>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 DC 1.0 Date' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 0.92 DC 1.1 Date' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 Atom 0.3 Created' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:created>2007-01-11T16:00:00Z</a:created>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 Atom 0.3 Issued' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:issued>2007-01-11T16:00:00Z</a:issued>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 Atom 0.3 Modified' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:modified>2007-01-11T16:00:00Z</a:modified>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 Atom 1.0 Published' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:published>2007-01-11T16:00:00Z</a:published>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 Atom 1.0 Updated' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:updated>2007-01-11T16:00:00Z</a:updated>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 DC 1.0 Date' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 1.0 DC 1.1 Date' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:date>2007-01-11T16:00:00Z</dc:date>
	</item>
</rdf:RDF>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 Atom 0.3 Created' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:created>2007-01-11T16:00:00Z</a:created>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 Atom 0.3 Issued' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:issued>2007-01-11T16:00:00Z</a:issued>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 Atom 0.3 Modified' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:modified>2007-01-11T16:00:00Z</a:modified>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 Atom 1.0 Published' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:published>2007-01-11T16:00:00Z</a:published>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 Atom 1.0 Updated' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:updated>2007-01-11T16:00:00Z</a:updated>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 DC 1.0 Date' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 DC 1.1 Date' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:date>2007-01-11T16:00:00Z</dc:date>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
			'Test RSS 2.0 pubDate' => [
<<<EOT
<rss version="2.0">
	<channel>
		<item>
			<pubDate>2007-01-11T16:00:00Z</pubDate>
		</item>
	</channel>
</rss>
EOT
				,
				1168531200,
			],
		];
	}

	/**
	 * @dataProvider getDateDataProvider
	 */
	public function test_get_date($data, $expected)
	{
		$feed = new SimplePie();
		$feed->set_raw_data($data);
		$feed->enable_cache(false);
		$feed->init();

		$item = $feed->get_item(0);
		$this->assertInstanceOf(Item::class, $item);

		$this->assertSame($expected, $item->get_date('U'));
	}

	public function getDescriptionDataProvider()
	{
		return [
			'Test Atom 0.3 Content' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<content>Item Description</content>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 DC 1.0 Description' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 DC 1.1 Description' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 0.3 Summary' => [
<<<EOT
<feed version="0.3" xmlns="http://purl.org/atom/ns#">
	<entry>
		<summary>Item Description</summary>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 Content' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<content>Item Description</content>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 DC 1.0 Description' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 DC 1.1 Description' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<entry>
		<dc:description>Item Description</dc:description>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test Atom 1.0 Summary' => [
<<<EOT
<feed xmlns="http://www.w3.org/2005/Atom">
	<entry>
		<summary>Item Description</summary>
	</entry>
</feed>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 0.3 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 0.3 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 1.0 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Atom 1.0 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 DC 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 DC 1.1 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.90 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://my.netscape.com/rdf/simple/0.9/">
	<item>
		<description>Item Description</description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 0.3 Content' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 0.3 Summary' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 1.0 Content' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Atom 1.0 Summary' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape DC 1.0 Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape DC 1.1 Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Netscape Description' => [
<<<EOT
<!DOCTYPE rss SYSTEM "http://my.netscape.com/publish/formats/rss-0.91.dtd">
<rss version="0.91">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 0.3 Content' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 0.3 Summary' => [
<<<EOT
<rss version="0.91" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 1.0 Content' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Atom 1.0 Summary' => [
<<<EOT
<rss version="0.91" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland DC 1.0 Description' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland DC 1.1 Description' => [
<<<EOT
<rss version="0.91" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.91-Userland Description' => [
<<<EOT
<rss version="0.91">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 0.3 Content' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 0.3 Summary' => [
<<<EOT
<rss version="0.92" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 1.0 Content' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Atom 1.0 Summary' => [
<<<EOT
<rss version="0.92" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 DC 1.0 Description' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 DC 1.1 Description' => [
<<<EOT
<rss version="0.92" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 0.92 Description' => [
<<<EOT
<rss version="0.92">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 0.3 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 0.3 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://purl.org/atom/ns#">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 1.0 Content' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:content>Item Description</a:content>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Atom 1.0 Summary' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:a="http://www.w3.org/2005/Atom">
	<item>
		<a:summary>Item Description</a:summary>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 DC 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 DC 1.1 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<item>
		<dc:description>Item Description</dc:description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 1.0 Description' => [
<<<EOT
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/">
	<item>
		<description>Item Description</description>
	</item>
</rdf:RDF>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 0.3 Content' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 0.3 Summary' => [
<<<EOT
<rss version="2.0" xmlns:a="http://purl.org/atom/ns#">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 1.0 Content' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:content>Item Description</a:content>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Atom 1.0 Summary' => [
<<<EOT
<rss version="2.0" xmlns:a="http://www.w3.org/2005/Atom">
	<channel>
		<item>
			<a:summary>Item Description</a:summary>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 DC 1.0 Description' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.0/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 DC 1.1 Description' => [
<<<EOT
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
	<channel>
		<item>
			<dc:description>Item Description</dc:description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
			'Test RSS 2.0 Description' => [
<<<EOT
<rss version="2.0">
	<channel>
		<item>
			<description>Item Description</description>
		</item>
	</channel>
</rss>
EOT
				,
				'Item Description',
			],
		];
	}

	/**
	 * @dataProvider getDescriptionDataProvider
	 */
	public function test_get_description($data, $expected)
	{
		$feed = new SimplePie();
		$feed->set_raw_data($data);
		$feed->enable_cache(false);
		$feed->init();

		$item = $feed->get_item(0);
		$this->assertInstanceOf(Item::class, $item);

		$this->assertSame($expected, $item->get_description());
	}
}
